import { writeFileSync } from "node:fs";
import path from "node:path";
import {
	ARCH_PACKETS,
	ARCHITECTURE_QUESTIONS,
	PRD_PACKETS,
	PRD_QUESTIONS,
	REQUIRED_ARCH,
	REQUIRED_PRD,
} from "./discovery-questions";
import {
	hasValue,
	renderArchitectureDoc,
	renderProductDoc,
} from "./discovery-renderers";
import { loadState, saveState } from "./planning";
import { repoRoot } from "./shared";
import type {
	DiscoveryAnswerBatch,
	DiscoveryQuestion,
	DiscoveryQuestionPacket,
	DiscoveryReadiness,
	DiscoveryState,
	HarnessState,
} from "./types";

function questionMap(): Record<string, DiscoveryQuestion> {
	return Object.fromEntries(
		[...PRD_QUESTIONS, ...ARCHITECTURE_QUESTIONS].map((question) => [
			question.id,
			question,
		]),
	);
}

export function evaluateDiscoveryReadiness(
	answered: Record<string, string>,
): DiscoveryReadiness {
	const productReady = REQUIRED_PRD.every((id) => hasValue(answered, id));
	const architectureReady = REQUIRED_ARCH.every((id) => hasValue(answered, id));
	return {
		productReady,
		architectureReady,
		planReady: productReady && architectureReady,
	};
}

function currentStage(readiness: DiscoveryReadiness): DiscoveryState["stage"] {
	if (!readiness.productReady) return "PRD";
	if (!readiness.architectureReady) return "ARCHITECTURE";
	return "COMPLETE";
}

function selectPacket(
	answered: Record<string, string>,
	packets: string[][],
	stage: "PRD" | "ARCHITECTURE",
): DiscoveryQuestionPacket | null {
	const map = questionMap();
	for (const packetIds of packets) {
		const unanswered = packetIds.filter((id) => !hasValue(answered, id));
		if (unanswered.length === 0) continue;
		return {
			stage,
			questionIds: unanswered,
			questions: unanswered.map((id) => map[id]),
			completionCriteria: evaluateDiscoveryReadiness(answered),
		};
	}
	return null;
}

export function nextDiscoveryPacket(
	state: HarnessState,
): DiscoveryQuestionPacket | null {
	const readiness = evaluateDiscoveryReadiness(state.discovery.answered);
	if (!readiness.productReady) {
		return selectPacket(state.discovery.answered, PRD_PACKETS, "PRD");
	}
	if (!readiness.architectureReady) {
		return selectPacket(state.discovery.answered, ARCH_PACKETS, "ARCHITECTURE");
	}
	return null;
}

function writeDiscoveryProgressDoc(root: string, state: HarnessState): void {
	const readiness = state.discovery.readiness;
	const nextPacket = nextDiscoveryPacket(state);
	const stage = state.discovery.stage;
	const progress = [
		"# Delivery Progress",
		"",
		"> Milestones and tasks are generated only after `docs/product.md` and `docs/architecture.md`",
		"> are complete enough to execute. This file is the human review surface; `.harness/state.json`",
		"> is the machine state canon.",
		"",
		"---",
		"",
		"## Planning Status",
		"",
		"| Surface | Status | Notes |",
		"|--------|--------|-------|",
		`| \`docs/product.md\` | ${readiness.productReady ? "Ready" : "Draft"} | ${readiness.productReady ? "PRD is complete enough to execute" : "Discovery is still filling PRD sections"} |`,
		`| \`docs/architecture.md\` | ${readiness.architectureReady ? "Ready" : "Draft"} | ${readiness.architectureReady ? "Architecture is complete enough to execute" : "Architecture questions have not completed yet"} |`,
		`| Discovery | ${stage} | ${nextPacket ? `Next questions: ${nextPacket.questionIds.join(", ")}` : "Discovery complete"} |`,
		`| Backlog sync | ${readiness.planReady ? "Ready" : "Blocked"} | ${readiness.planReady ? "Run `bun run harness:plan`" : "Finish discovery before planning"} |`,
		"",
		"---",
		"",
		"## Milestones",
		"",
		"| Milestone | Goal | Status | Depends On | Parallel | Worktree |",
		"|-----------|------|--------|------------|----------|----------|",
		"| *(generated by `harness:plan`)* | - | - | - | - | - |",
		"",
		"---",
		"",
		"## Tasks",
		"",
		"| Task | Milestone | Kind | Status | Validation | Notes |",
		"|------|-----------|------|--------|------------|-------|",
		"| *(generated by `harness:plan`)* | - | - | - | - | - |",
		"",
		"---",
		"",
		"## Active Worktrees",
		"",
		"| Worktree | Milestone | Branch | Status |",
		"|----------|-----------|--------|--------|",
		"| *(created by `harness:parallel-dispatch` when milestone parallelism is enabled)* | - | - | - |",
		"",
		"---",
		"",
		"## Activity Log",
		"",
		`- Discovery updated on ${state.discovery.lastUpdatedAt ?? "[date]"}.`,
	].join("\n");

	writeFileSync(path.join(root, "docs/progress.md"), `${progress}\n`);
}

export function resetDiscoveryState(state: HarnessState): HarnessState {
	state.discovery = {
		stage: "PRD",
		status: "idle",
		currentQuestionIds: [],
		answered: {},
		history: [],
		readiness: {
			productReady: false,
			architectureReady: false,
			planReady: false,
		},
		lastUpdatedAt: null,
	};
	state.planning.phase = "DISCOVERY";
	state.planning.docsReady = {
		product: false,
		architecture: false,
		backlog: false,
	};
	state.milestones = [];
	state.tasks = [];
	state.execution.activeMilestones = [];
	state.execution.activeWorktrees = [];
	state.skills.loaded = [];
	return state;
}

export function applyDiscoveryAnswers(
	root: string,
	batch: DiscoveryAnswerBatch,
): HarnessState {
	const state = loadState(root);
	for (const answer of batch.answers) {
		state.discovery.answered[answer.id] = answer.value.trim();
	}

	const readiness = evaluateDiscoveryReadiness(state.discovery.answered);
	state.discovery.readiness = readiness;
	state.discovery.stage = currentStage(readiness);
	state.discovery.status = readiness.planReady
		? "ready_for_plan"
		: "collecting";
	state.discovery.history.push({
		stage: state.discovery.stage,
		questionIds: batch.answers.map((answer) => answer.id),
		answeredAt: new Date().toISOString(),
	});
	state.discovery.lastUpdatedAt = new Date().toISOString();

	const nextPacket = nextDiscoveryPacket(state);
	state.discovery.currentQuestionIds = nextPacket?.questionIds ?? [];
	state.planning.docsReady = {
		product: readiness.productReady,
		architecture: readiness.architectureReady,
		backlog: readiness.planReady,
	};

	writeFileSync(
		path.join(root, "docs/product.md"),
		`${renderProductDoc(state.discovery.answered)}\n`,
	);
	writeFileSync(
		path.join(root, "docs/architecture.md"),
		`${renderArchitectureDoc(state.discovery.answered)}\n`,
	);
	writeDiscoveryProgressDoc(root, state);
	saveState(root, state);
	return state;
}

export function nextPacketJson(root: string): DiscoveryQuestionPacket | null {
	const state = loadState(root);
	const readiness = evaluateDiscoveryReadiness(state.discovery.answered);
	state.discovery.readiness = readiness;
	state.discovery.stage = currentStage(readiness);
	const packet = nextDiscoveryPacket(state);
	state.discovery.currentQuestionIds = packet?.questionIds ?? [];
	state.discovery.status = readiness.planReady
		? "ready_for_plan"
		: "collecting";
	saveState(root, state);
	return packet;
}

export function resetDiscovery(root: string = repoRoot()): HarnessState {
	const state = resetDiscoveryState(loadState(root));
	writeFileSync(
		path.join(root, "docs/product.md"),
		`${renderProductDoc({})}\n`,
	);
	writeFileSync(
		path.join(root, "docs/architecture.md"),
		`${renderArchitectureDoc({})}\n`,
	);
	writeDiscoveryProgressDoc(root, state);
	saveState(root, state);
	return state;
}
