export function hasValue(
	answered: Record<string, string>,
	id: string,
): boolean {
	return Boolean(answered[id]?.trim());
}

function sectionValue(
	answered: Record<string, string>,
	id: string,
	fallback: string,
): string {
	return hasValue(answered, id) ? answered[id].trim() : fallback;
}

export function renderProductDoc(answered: Record<string, string>): string {
	return [
		"# Product Requirements Document",
		"",
		"> This document is a living spec. Update it when requirements change.",
		"> Agents read this to understand *what* is being built and *why*.",
		"",
		"---",
		"",
		"## Executive Summary",
		"",
		sectionValue(
			answered,
			"prd.executive-summary",
			"**[PROJECT_NAME]** is a [type of product] that helps [target users] to [accomplish goal] by [core mechanism].",
		),
		"",
		"---",
		"",
		"## Problem Statement",
		"",
		sectionValue(
			answered,
			"prd.problem-statement",
			"**Current state:** [Describe the status quo]\n\n**The gap:** [Describe what's missing or broken]\n\n**Impact:** [Describe consequences of the gap — lost time, revenue, user frustration, etc.]",
		),
		"",
		"---",
		"",
		"## Target Audience",
		"",
		sectionValue(
			answered,
			"prd.target-audience",
			"| Persona | Description | Primary Goal |\n|---------|-------------|--------------|\n| [Persona 1] | [Description] | [Goal] |\n| [Persona 2] | [Description] | [Goal] |",
		),
		"",
		"---",
		"",
		"## Core Capabilities",
		"",
		sectionValue(
			answered,
			"prd.core-capabilities",
			"### Must Have (v1)\n- [ ] [Capability 1]\n- [ ] [Capability 2]\n\n### Should Have (v1)\n- [ ] [Capability 3]\n\n### Could Have (later)\n- [ ] [Capability 4]\n\n### Won't Have (out of scope)\n- [Explicitly excluded thing]",
		),
		"",
		"---",
		"",
		"## Proposed Milestones",
		"",
		sectionValue(
			answered,
			"prd.proposed-milestones",
			"- [ ] [Milestone 1] — [Goal / shipped outcome]\n- [ ] [Milestone 2] — [Goal / shipped outcome]",
		),
		"",
		"---",
		"",
		"## Scope Boundaries",
		"",
		sectionValue(
			answered,
			"prd.scope-boundaries",
			"**In scope:**\n- [What is explicitly included]\n\n**Out of scope:**\n- [What is explicitly excluded and why]",
		),
		"",
		"---",
		"",
		"## Success Metrics",
		"",
		sectionValue(
			answered,
			"prd.success-metrics",
			"| Metric | Baseline | Target | Timeline |\n|--------|----------|--------|----------|\n| [Metric 1] | [Current] | [Goal] | [When] |\n| [Metric 2] | [Current] | [Goal] | [When] |",
		),
		"",
		"---",
		"",
		"## Assumptions & Constraints",
		"",
		sectionValue(
			answered,
			"prd.assumptions-constraints",
			"**Assumptions:**\n- [Assumption 1]\n- [Assumption 2]\n\n**Constraints:**\n- [Technical constraint]\n- [Resource constraint]\n- [Timeline constraint]",
		),
		"",
		"---",
		"",
		"## Open Questions",
		"",
		sectionValue(
			answered,
			"prd.open-questions",
			"- [ ] [Question 1] — *Owner: [name], Due: [date]*\n- [ ] [Question 2] — *Owner: [name], Due: [date]*",
		),
		"",
		"---",
		"",
		"## Planning Readiness Checklist",
		"",
		`- [${hasValue(answered, "prd.executive-summary") ? "x" : " "}] Product goals are explicit`,
		`- [${hasValue(answered, "prd.scope-boundaries") ? "x" : " "}] In-scope vs out-of-scope is explicit`,
		`- [${hasValue(answered, "prd.success-metrics") ? "x" : " "}] Success metrics are explicit`,
		`- [${hasValue(answered, "prd.proposed-milestones") ? "x" : " "}] Proposed milestones are listed`,
		`- [${hasValue(answered, "prd.problem-statement") ? "x" : " "}] No critical unknown blocks architecture work`,
		"",
		"---",
		"",
		"*Last updated: [date] | Owner: [name]*",
	].join("\n");
}

export function renderArchitectureDoc(
	answered: Record<string, string>,
): string {
	return [
		"# System Architecture",
		"",
		"> This document describes *how* the system is structured, not *what* it does (that's `product.md`).",
		"> Agents read this to understand constraints before implementing.",
		"",
		"---",
		"",
		"## Architecture Overview",
		"",
		sectionValue(
			answered,
			"arch.overview",
			"```\n[User / Client]\n       │\n       ▼\n  ┌─────────┐\n  │   UI    │\n  └────┬────┘\n       │\n  ┌────▼────┐\n  │ Service │\n  └────┬────┘\n       │\n  ┌────▼────┐\n  │  Repo   │\n  └────┬────┘\n       │\n  ┌────▼────┐\n  │ Config  │\n  └────┬────┘\n       │\n  ┌────▼────┐\n  │  Types  │\n  └─────────┘\n```",
		),
		"",
		"---",
		"",
		"## Dependency Layer Model",
		"",
		"This project enforces a strict dependency layer order. See `harness/rules/dependency-layers.json` for machine-readable rules.",
		"",
		"```",
		"Types → Config → Repo → Service → Runtime → UI",
		"```",
		"",
		"**Rule:** Each layer may only import from layers below (to the left) of it.",
		"**Enforcement:** `bun run harness:lint` checks this on every commit.",
		"",
		"| Layer | Directory | Allowed Imports |",
		"|-------|-----------|-----------------|",
		"| `types` | `src/types/` | (none — foundational) |",
		"| `config` | `src/config/` | `types` |",
		"| `repo` | `src/repo/` | `types`, `config` |",
		"| `service` | `src/service/` | `types`, `config`, `repo` |",
		"| `runtime` | `src/runtime/` | `types`, `config`, `repo`, `service` |",
		"| `ui` | `src/ui/` | all layers |",
		"",
		"---",
		"",
		"## System Boundaries",
		"",
		sectionValue(
			answered,
			"arch.system-boundaries",
			"| System | Direction | Protocol | Notes |\n|--------|-----------|----------|-------|\n| [External system 1] | inbound | [HTTP/gRPC/etc] | [notes] |\n| [External system 2] | outbound | [HTTP/gRPC/etc] | [notes] |",
		),
		"",
		"---",
		"",
		"## Interfaces & Contracts",
		"",
		sectionValue(
			answered,
			"arch.interfaces-contracts",
			"### [Interface 1]\n```\n[Schema or API signature]\n```",
		),
		"",
		"---",
		"",
		"## Execution Constraints",
		"",
		sectionValue(
			answered,
			"arch.execution-constraints",
			"| Constraint | Impact on Milestones | Notes |\n|-----------|----------------------|-------|\n| [Shared migration / external dependency / lock] | [Why it blocks or serializes work] | [notes] |",
		),
		"",
		"---",
		"",
		"## Cross-Cutting Concerns",
		"",
		sectionValue(
			answered,
			"arch.cross-cutting",
			"| Concern | Approach |\n|---------|----------|\n| **Logging** | Structured JSON logs, no `console.log` in production |\n| **Error handling** | Errors typed at system boundaries, propagate as values inside |\n| **Authentication** | [Your approach] |\n| **Configuration** | Environment variables via `.env`, validated at startup |",
		),
		"",
		"---",
		"",
		"## Build / Distribution / Deployment",
		"",
		sectionValue(
			answered,
			"arch.build-distribution-deployment",
			"```bash\n# Build\n[your build command]\n\n# Test\n[your test command]\n\n# Deploy\n[your deploy command]\n```",
		),
		"",
		"---",
		"",
		"## Technical Risks",
		"",
		sectionValue(
			answered,
			"arch.technical-risks",
			"| Risk | Likelihood | Impact | Mitigation |\n|------|-----------|--------|------------|\n| [Risk 1] | High/Med/Low | High/Med/Low | [Mitigation] |",
		),
		"",
		"---",
		"",
		"## Validation Plan",
		"",
		sectionValue(
			answered,
			"arch.validation-plan",
			"1. `bun run harness:structural` — structural compliance\n2. `bun run harness:lint` — linting and rule checks\n3. `bun run harness:validate` — full harness validation",
		),
		"",
		"---",
		"",
		"## Architecture Readiness Checklist",
		"",
		`- [${hasValue(answered, "arch.system-boundaries") ? "x" : " "}] System boundaries are explicit`,
		`- [${hasValue(answered, "arch.overview") ? "x" : " "}] Dependency direction is explicit`,
		`- [${hasValue(answered, "arch.interfaces-contracts") ? "x" : " "}] Interfaces/contracts are explicit enough to implement`,
		`- [${hasValue(answered, "arch.execution-constraints") ? "x" : " "}] Execution constraints for milestone splitting are explicit`,
		`- [${hasValue(answered, "arch.validation-plan") ? "x" : " "}] No critical architecture unknown blocks backlog generation`,
		"",
		"---",
		"",
		"*Last updated: [date] | Owner: [name]*",
	].join("\n");
}
