import { appendFileSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { runCommandWithCapture } from "./command-runner";
import { buildDocsReport } from "./docs-report";
import { collectGoldenPrincipleFindings } from "./golden-principles";
import { writeReportArtifact } from "./report-artifacts";
import { repoRoot, trackedFiles } from "./shared";
import type {
	QualityDimensionDefinition,
	QualityDimensionScore,
	QualityReport,
} from "./types";
import { runLayerLint, validationContext } from "./validation";
import {
	collectFileSizeViolations,
	collectForbiddenPatternViolations,
} from "./validation-reports";

function captureLayerLint(root: string): boolean {
	const context = validationContext(root);
	const original = console.log;
	console.log = () => {};
	try {
		return runLayerLint(context) === 0;
	} finally {
		console.log = original;
	}
}

async function explicitAnyCount(root: string): Promise<number> {
	let count = 0;
	for (const relativePath of trackedFiles(root).filter((file) =>
		/\.(ts|tsx)$/.test(file),
	)) {
		const content = await Bun.file(path.join(root, relativePath)).text();
		count += (content.match(/\bany\b/g) ?? []).length;
	}
	return count;
}

function gradeForScore(
	grading: Record<string, { min: number; label: string }>,
	score: number,
): string {
	return (
		Object.entries(grading)
			.sort((left, right) => right[1].min - left[1].min)
			.find(([, value]) => score >= value.min)?.[0] ?? "F"
	);
}

function renderGradesDoc(report: QualityReport): string {
	return [
		"# Quality Grades",
		"",
		"Auto-generated by `bun run harness:quality --update`.",
		"",
		`**Last updated:** ${report.generatedAt} | **Overall grade:** ${report.overallGrade} (${report.overallScore.toFixed(1)}/100)`,
		"",
		"---",
		"",
		"## Dimensions",
		"",
		"| Dimension | Score | Detail |",
		"|-----------|-------|--------|",
		...report.dimensions.map(
			(dimension) =>
				`| ${dimension.label} | ${dimension.score.toFixed(1)} | ${dimension.detail} |`,
		),
		"",
	].join("\n");
}

async function scoreDimension(
	root: string,
	definition: QualityDimensionDefinition,
): Promise<QualityDimensionScore> {
	const context = validationContext(root);

	if (definition.name === "type_safety") {
		const typecheck = runCommandWithCapture({
			root,
			commandLine: "bun run typecheck",
			logCategory: "quality-typecheck",
			maxSnippetLines: 8,
		});
		const anyCount = await explicitAnyCount(root);
		const baseScore = typecheck.exitCode === 0 ? 100 : 40;
		return {
			name: definition.name,
			label: definition.label,
			score: Math.max(0, baseScore - anyCount),
			weight: definition.weight,
			detail:
				typecheck.exitCode === 0
					? `typecheck passed, ${anyCount} explicit any marker(s)`
					: `typecheck failed, ${anyCount} explicit any marker(s)`,
		};
	}

	if (definition.name === "test_health") {
		const structural = runCommandWithCapture({
			root,
			commandLine: "bun run harness:structural",
			logCategory: "quality-structural",
			maxSnippetLines: 8,
		});
		const sourceFiles = trackedFiles(root).filter((file) =>
			/\.(ts|tsx|js|jsx)$/.test(file),
		).length;
		const testFiles = trackedFiles(root).filter((file) =>
			/\.(test|spec)\.[cm]?[jt]sx?$/.test(file),
		).length;
		const ratio =
			sourceFiles === 0 ? 100 : Math.min(100, (testFiles / sourceFiles) * 400);
		return {
			name: definition.name,
			label: definition.label,
			score: structural.exitCode === 0 ? ratio : Math.min(ratio, 55),
			weight: definition.weight,
			detail: `${testFiles} test file(s), ${sourceFiles} source file(s), structural ${
				structural.exitCode === 0 ? "passed" : "failed"
			}`,
		};
	}

	if (definition.name === "architectural_compliance") {
		const passed = captureLayerLint(root);
		return {
			name: definition.name,
			label: definition.label,
			score: passed ? 100 : 50,
			weight: definition.weight,
			detail: passed ? "Layer lint passed." : "Layer lint failed.",
		};
	}

	if (definition.name === "entropy_score") {
		const findings = collectGoldenPrincipleFindings(context);
		const errors = findings.filter(
			(finding) => finding.severity === "error",
		).length;
		const warnings = findings.length - errors;
		return {
			name: definition.name,
			label: definition.label,
			score: Math.max(0, 100 - errors * 20 - warnings * 8),
			weight: definition.weight,
			detail: `${findings.length} golden-principle finding(s)`,
		};
	}

	if (definition.name === "doc_freshness") {
		const report = buildDocsReport(context);
		const errors = report.freshness.filter(
			(finding) => finding.severity === "error",
		).length;
		const warnings = report.freshness.filter(
			(finding) => finding.severity === "warning",
		).length;
		const infos = report.freshness.filter(
			(finding) => finding.severity === "info",
		).length;
		return {
			name: definition.name,
			label: definition.label,
			score: Math.max(
				0,
				100 -
					errors * 30 -
					warnings * 10 -
					infos * 3 -
					report.brokenLinks.length * 15,
			),
			weight: definition.weight,
			detail: `${report.freshness.length} freshness finding(s), ${report.brokenLinks.length} broken link(s)`,
		};
	}

	if (definition.name === "code_hygiene") {
		const fileSizeViolations = collectFileSizeViolations(context);
		const forbiddenViolations = collectForbiddenPatternViolations(context);
		return {
			name: definition.name,
			label: definition.label,
			score: Math.max(
				0,
				100 - fileSizeViolations.length * 15 - forbiddenViolations.length * 12,
			),
			weight: definition.weight,
			detail: `${fileSizeViolations.length} file-size violation(s), ${forbiddenViolations.length} forbidden-pattern violation(s)`,
		};
	}

	return {
		name: definition.name,
		label: definition.label,
		score: 100,
		weight: definition.weight,
		detail: definition.measurement,
	};
}

export async function buildQualityReport(
	root: string = repoRoot(),
): Promise<QualityReport> {
	const context = validationContext(root);
	const definitions = context.qualityDimensions?.dimensions ?? [];
	const dimensions = await Promise.all(
		definitions.map((definition) => scoreDimension(root, definition)),
	);
	const overallScore = dimensions.reduce(
		(total, dimension) => total + dimension.score * dimension.weight,
		0,
	);
	const overallGrade = gradeForScore(
		context.qualityDimensions?.grading ?? {
			A: { min: 90, label: "Excellent" },
			B: { min: 75, label: "Good" },
			C: { min: 60, label: "Needs attention" },
			D: { min: 40, label: "At risk" },
			F: { min: 0, label: "Critical" },
		},
		overallScore,
	);
	return {
		version: "1.0.0",
		generatedAt: new Date().toISOString(),
		overallScore,
		overallGrade,
		dimensions,
	};
}

async function main(): Promise<void> {
	const root = repoRoot();
	const report = await buildQualityReport(root);
	const reportPath = writeReportArtifact(
		root,
		"quality",
		"latest-report.json",
		report,
	);
	const jsonMode = process.argv.includes("--json");
	const updateMode = process.argv.includes("--update");

	if (updateMode) {
		const context = validationContext(root);
		const gradesPath =
			context.config.quality?.gradesPath ?? "docs/quality/GRADES.md";
		const historyPath =
			context.config.quality?.historyPath ?? ".harness/quality/history.jsonl";
		const absoluteGradesPath = path.join(root, gradesPath);
		const absoluteHistoryPath = path.join(root, historyPath);
		mkdirSync(path.dirname(absoluteGradesPath), { recursive: true });
		writeFileSync(absoluteGradesPath, `${renderGradesDoc(report)}\n`);
		mkdirSync(path.dirname(absoluteHistoryPath), { recursive: true });
		appendFileSync(absoluteHistoryPath, `${JSON.stringify(report)}\n`);
	}

	if (jsonMode) {
		console.log(JSON.stringify({ ...report, reportPath }, null, 2));
		return;
	}

	console.log("harness quality");
	console.log("════════════════════════════════════════════");
	console.log(
		`Overall: ${report.overallGrade} (${report.overallScore.toFixed(1)}/100)`,
	);
	for (const dimension of report.dimensions) {
		console.log(
			`- ${dimension.label}: ${dimension.score.toFixed(1)} — ${dimension.detail}`,
		);
	}
	console.log("");
	console.log(`Report artifact: ${reportPath}`);
}

void main();
